# .github/workflows/ci-lint.yml

name: CI - Lint & Format

# This workflow runs on every push to any branch, and on any pull requests.
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ruff:
    name: Ruff Lint & Format
    # The job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # This creates a build matrix to test against multiple Python versions,
    # ensuring broad compatibility.
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      # Step 1: Check out the repository code so the workflow can access it.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the specified Python version from the matrix.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Cache dependencies to speed up subsequent runs.
      # The cache is invalidated if the Python version or pyproject.toml changes.
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      # Step 4: Install the project dependencies, including the [test] extras.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      # Step 5: Run Ruff lint and format.
      - name: Ruff lint
        run: ruff check .

      - name: Ruff format (check only)
        run: ruff format --check .
